import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export async function seedAula() {
  console.log('🌱 Seeding Aula...');

  const data: any[] = [
    {
      c_codaula: '1',
      n_piso: -1,
      pabellon: 'B',
      n_capacidad: '45',
      c_obs: null,
    },
    {
      c_codaula: '2',
      n_piso: -1,
      pabellon: 'B',
      n_capacidad: '45',
      c_obs: null,
    },
    {
      c_codaula: '3',
      n_piso: -1,
      pabellon: 'B',
      n_capacidad: '60',
      c_obs: null,
    },
    {
      c_codaula: 'AUDITORIA',
      n_piso: -1,
      pabellon: 'B',
      n_capacidad: '60',
      c_obs: null,
    },
    {
      c_codaula: 'LAB COMPUTO',
      n_piso: -1,
      pabellon: 'C',
      n_capacidad: '60',
      c_obs: null,
    },
    {
      c_codaula: '101',
      n_piso: 1,
      pabellon: 'B',
      n_capacidad: '45',
      c_obs: null,
    },
    {
      c_codaula: '102',
      n_piso: 1,
      pabellon: 'B',
      n_capacidad: '45',
      c_obs: null,
    },
    {
      c_codaula: '103',
      n_piso: 1,
      pabellon: 'B',
      n_capacidad: '50',
      c_obs: null,
    },
    {
      c_codaula: '104',
      n_piso: 1,
      pabellon: 'B',
      n_capacidad: '50',
      c_obs: null,
    },
    //2
    {
      c_codaula: '201',
      n_piso: 2,
      pabellon: 'B',
      n_capacidad: '25',
      c_obs: null,
    },
    {
      c_codaula: '202',
      n_piso: 2,
      pabellon: 'B',
      n_capacidad: '25',
      c_obs: null,
    },
    {
      c_codaula: '203',
      n_piso: 2,
      pabellon: 'B',
      n_capacidad: '45',
      c_obs: null,
    },
    {
      c_codaula: '204',
      n_piso: 2,
      pabellon: 'B',
      n_capacidad: '25',
      c_obs: null,
    },
    {
      c_codaula: '205',
      n_piso: 2,
      pabellon: 'B',
      n_capacidad: '50',
      c_obs: null,
    },
    {
      c_codaula: '206',
      n_piso: 2,
      pabellon: 'B',
      n_capacidad: '25',
      c_obs: null,
    },
    //3
    {
      c_codaula: '301',
      n_piso: 3,
      pabellon: 'A',
      n_capacidad: '15',
      c_obs: null,
    },
    {
      c_codaula: '302',
      n_piso: 3,
      pabellon: 'A',
      n_capacidad: '15',
      c_obs: null,
    },
    {
      c_codaula: '303',
      n_piso: 3,
      pabellon: 'A',
      n_capacidad: '40',
      c_obs: null,
    },
    {
      c_codaula: '304',
      n_piso: 3,
      pabellon: 'B',
      n_capacidad: '25',
      c_obs: null,
    },
    {
      c_codaula: '305',
      n_piso: 3,
      pabellon: 'B',
      n_capacidad: '25',
      c_obs: null,
    },
    {
      c_codaula: '306',
      n_piso: 3,
      pabellon: 'B',
      n_capacidad: '45',
      c_obs: null,
    },
    {
      c_codaula: '307',
      n_piso: 3,
      pabellon: 'B',
      n_capacidad: '25',
      c_obs: null,
    },
    {
      c_codaula: '308',
      n_piso: 3,
      pabellon: 'B',
      n_capacidad: '50',
      c_obs: null,
    },
    {
      c_codaula: '309',
      n_piso: 3,
      pabellon: 'B',
      n_capacidad: '25',
      c_obs: null,
    },
    //4
    {
      c_codaula: '401',
      n_piso: 4,
      pabellon: 'A',
      n_capacidad: 'REUNIONES',
      c_obs: 'Sala de reuniones',
    },
    {
      c_codaula: '402',
      n_piso: 4,
      pabellon: 'A',
      n_capacidad: 'REUNIONES',
      c_obs: 'Sala de reuniones',
    },
    {
      c_codaula: '403',
      n_piso: 4,
      pabellon: 'A',
      n_capacidad: '40',
      c_obs: null,
    },
    {
      c_codaula: '404',
      n_piso: 4,
      pabellon: 'B',
      n_capacidad: '25',
      c_obs: null,
    },
    {
      c_codaula: '405',
      n_piso: 4,
      pabellon: 'B',
      n_capacidad: '25',
      c_obs: null,
    },
    {
      c_codaula: '406',
      n_piso: 4,
      pabellon: 'B',
      n_capacidad: '40',
      c_obs: null,
    },
    {
      c_codaula: '407',
      n_piso: 4,
      pabellon: 'B',
      n_capacidad: '50',
      c_obs: null,
    },
    //camara
    {
      c_codaula: 'CAMARA GESSEL 1',
      n_piso: 4,
      pabellon: 'B',
      n_capacidad: '20',
      c_obs: null,
    },
    {
      c_codaula: 'CAMARA GESSEL 2',
      n_piso: 4,
      pabellon: 'B',
      n_capacidad: '20',
      c_obs: null,
    },
    //5
    {
      c_codaula: '501',
      n_piso: 5,
      pabellon: 'A',
      n_capacidad: '40',
      c_obs: null,
    },
    {
      c_codaula: '502',
      n_piso: 5,
      pabellon: 'A',
      n_capacidad: '40',
      c_obs: null,
    },
    {
      c_codaula: '503',
      n_piso: 5,
      pabellon: 'B',
      n_capacidad: 'GRABACIÓN',
      c_obs: 'Sala grabación',
    },
    {
      c_codaula: '504',
      n_piso: 5,
      pabellon: 'B',
      n_capacidad: 'SISTEMAS',
      c_obs: 'Oficina',
    },
    {
      c_codaula: '505',
      n_piso: 5,
      pabellon: 'B',
      n_capacidad: '45',
      c_obs: null,
    },
    {
      c_codaula: '506',
      n_piso: 5,
      pabellon: 'B',
      n_capacidad: 'EDUCACIÓN VIRTUAL',
      c_obs: 'Oficina',
    },
    {
      c_codaula: '507',
      n_piso: 5,
      pabellon: 'B',
      n_capacidad: '50',
      c_obs: null,
    },
    {
      c_codaula: '508',
      n_piso: 5,
      pabellon: 'B',
      n_capacidad: 'REUNIONES',
      c_obs: 'Sala reuniones',
    },
    //6
    {
      c_codaula: '601',
      n_piso: 6,
      pabellon: 'A',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    {
      c_codaula: '602',
      n_piso: 6,
      pabellon: 'A',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    {
      c_codaula: '603',
      n_piso: 6,
      pabellon: 'B',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    {
      c_codaula: '604',
      n_piso: 6,
      pabellon: 'B',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    {
      c_codaula: '605',
      n_piso: 6,
      pabellon: 'B',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    {
      c_codaula: '606',
      n_piso: 6,
      pabellon: 'B',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    //7
    {
      c_codaula: '701',
      n_piso: 7,
      pabellon: 'A',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    {
      c_codaula: '702',
      n_piso: 7,
      pabellon: 'A',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    {
      c_codaula: '703',
      n_piso: 7,
      pabellon: 'B',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    {
      c_codaula: '704',
      n_piso: 7,
      pabellon: 'B',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    {
      c_codaula: '705',
      n_piso: 7,
      pabellon: 'B',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    {
      c_codaula: '706',
      n_piso: 7,
      pabellon: 'B',
      n_capacidad: 'SIN EQUIPAR',
      c_obs: 'No autorizado',
    },
    //lab
    {
      c_codaula: 'SL01-LA02 (1A)',
      n_piso: 1,
      pabellon: 'C',
      n_capacidad: '25',
      c_obs: 'Química y Bioquímica',
    },
    {
      c_codaula: 'SL01-LA08 (1B)',
      n_piso: 1,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Ciencias de la Salud I',
    },
    {
      c_codaula: 'SL01-LA03 (2A)',
      n_piso: 2,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Anatomía Humana',
    },
    {
      c_codaula: 'SL01-LA09 (2B)',
      n_piso: 2,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Ciencias de la Salud II',
    },
    {
      c_codaula: 'SL01-LA10 (3A)',
      n_piso: 3,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Ciencias de la Salud III',
    },
    {
      c_codaula: 'SL01-LA12 (3B)',
      n_piso: 3,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Ciencias de la Salud V',
    },
    {
      c_codaula: 'SL01-LA04 (4A)',
      n_piso: 4,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Ciencias Químicas',
    },
    {
      c_codaula: 'SL01-LA11 (4B)',
      n_piso: 4,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Ciencias de la Salud IV',
    },
    {
      c_codaula: 'SL01-LA05 (5A)',
      n_piso: 5,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Simulador - Gabinete de Enfermería',
    },
    {
      c_codaula: 'SL01LA07 (5B)',
      n_piso: 5,
      pabellon: 'C',
      n_capacidad: '20',
      c_obs: 'Nutrición y Dietética',
    },
    {
      c_codaula: 'SL01-LA13 (6A)',
      n_piso: 6,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Ciencias de la Salud VI', //
    },
    {
      c_codaula: 'SL01-LA14 (6B)',
      n_piso: 6,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Ciencias de la Salud VII',
    },
    {
      c_codaula: 'SL01-LA15 (7A)',
      n_piso: 7,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Gabinete de Terapia Física',
    },
    {
      c_codaula: 'SL01-LA16 (7B)',
      n_piso: 8,
      pabellon: 'C',
      n_capacidad: '30',
      c_obs: 'Ciencias de la Salud VIII',
    },
  ];

  const result = await prisma.aula.createMany({
    data,
    skipDuplicates: true,
  });

  console.log('✅ Aulas insertadas:', result);
}
